# server config
server:
  port: 8080
spring:
  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/diary
  # form input method
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      location: C:\dev\project\diary\src\main\resources\static\img
      max-file-size: 200MB
      max-request-size: 100MB
# mybatis config
mybatis:
  type-aliases-package: kr.co.space.diary.entity
  mapper-locations: classpath:mappers/**/*.xml